apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tfchainportal.fullname" . }}
  labels:
    {{- include "tfchainportal.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "tfchainportal.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "tfchainportal.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: VUE_APP_API_URL
            value: {{ .Values.url }}
          - name: VUE_APP_ACTIVATION_SERVICE_URL
            value: {{ .Values.activation_url }}
          - name: VUE_APP_STELLAR_HORIZON_URL
            value: {{ .Values.stellar_horizon_url }}
          - name: VUE_APP_TFT_ASSET_ISSUER
            value: {{ .Values.tft_asset_issuer }}
          - name: VUE_APP_BRIDGE_TFT_ADDRESS
            value: {{ .Values.stellar_bridge_address }}
          - name: VUE_APP_EXPLORER_URL
            value: {{ .Values.explorer_url }}
          - name: VUE_APP_GRAPHQL_URL
            value: {{ .Values.grapqhl_url }}
          - name: VUE_APP_GRIDPROXY_URL
            value: {{ .Values.gridproxy_url }}
          - name: VUE_APP_NETWORK
            value: {{ .Values.network }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
